const ActionTypes = {
    PRODUCT_LOADING: "PRODUCT_LOADING",
    PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
    PRODUCT_ERROR: "PRODUCT_ERROR",
    REST_LOADING: "REST_LOADING",
    REST_SUCCESS: "REST_SUCCESS",
    REST_ERROR: "REST_ERROR",
    ADD_TO_CART: "ADD_TO_CART",
    UPDATE_CART: "UPDATE_CART",
    ERROR_CART: "ERROR_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
}

export default ActionTypes